steps:
- id: 'git-repo-status'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$REPO_NAME"
      echo "$BRANCH_NAME"
      echo "***********************"

- name: gcr.io/k8s-skaffold/skaffold:v2.0.5
  id: skaffoldBuild
  args:
    - "skaffold"
    - "build"
    - "--file-output=/workspace/artifacts.json"
    - "--default-repo=${_DEPLOY_PIPELINE_REGION}-docker.pkg.dev/prj-zeld-infra-core/$_ARTIFACT_REPONAME"
    - "--module=$_DEPLOY_PIPELINE"

- id: 'gcloudDeployDev'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  dir: /workspace
  waitFor:
  - skaffoldBuild
  args:
  - '-c'
  - |
      gcloud deploy releases create "$_DEPLOY_PIPELINE-$SHORT_SHA"  \
        --delivery-pipeline="$_DEPLOY_PIPELINE" \
        --build-artifacts=/workspace/artifacts.json \
        --skaffold-file="$_DEPLOY_SVC/skaffold.yaml" \
        --skaffold-version="2.0" \
        --region="${_DEPLOY_PIPELINE_REGION}" &&
        echo "$_DEPLOY_PIPELINE-$SHORT_SHA" > /workspace/.cb.releasename

options:
  # This allows for missing ENV variables.
  substitution_option: 'ALLOW_LOOSE'
