apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: space-agon-leaderboard
  annotations:
    about: Leaderboard service for space-agon
  labels:
    lang: go
description: |
  Delivery pipeline for CI CD app (in Go)
serialPipeline:
 stages:
  - targetId: apac
    profiles: [apac]
  - targetId: emea
    profiles: [emea]
  - targetId: northam
    profiles: [northam]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: apac
description: APAC cluster (testing, load testing, feature feedback)
gke:
  cluster: projects/prj-zeld-gke/locations/asia-northeast1/clusters/gke-asia-northeast1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: northam
description:  |
  NORTHAM cluster (full launch)
requireApproval: true
gke:
  cluster: projects/prj-zeld-gke/locations/us-west1/clusters/gke-us-west1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: emea
description:  |
  EMEA cluster (full launch)
gke:
  cluster: projects/prj-zeld-gke/locations/europe-west1/clusters/gke-europe-west1
